name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Copy static files to deploy directory
        run: |
          mkdir -p ./deploy
          cp -r ./static/* ./deploy/
          cp ./static/index.html ./deploy/
          cp ./LICENSE ./deploy/
          cp ./README.md ./deploy/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 