name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Copy static files to deploy directory
        run: |
          mkdir -p ./deploy
          cp -r ./static/* ./deploy/
          # Make sure index.html is at the root level
          if [ -f ./static/index.html ]; then
            echo "Found index.html in static directory, copying to deploy directory"
            cp ./static/index.html ./deploy/index.html
          else
            echo "WARNING: index.html not found in static directory"
            ls -la ./static/
          fi
          
          # Copy root index.html as a fallback
          if [ -f ./index.html ]; then
            echo "Found root index.html, copying to deploy directory"
            # Keep the original but also make a copy as 'root-index.html' for reference
            cp ./index.html ./deploy/root-index.html
            
            # If no index.html exists yet, use the root one
            if [ ! -f ./deploy/index.html ]; then
              cp ./index.html ./deploy/index.html
            fi
          fi
          
          # Create a .nojekyll file to disable Jekyll processing
          touch ./deploy/.nojekyll
          echo "Created .nojekyll file to disable Jekyll processing"
          
          # Copy additional files
          cp ./LICENSE ./deploy/ || echo "LICENSE file not copied"
          cp ./README.md ./deploy/ || echo "README file not copied"
          
          echo "Contents of deploy directory:"
          ls -la ./deploy/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 