name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Copy static files to deploy directory
        run: |
          mkdir -p ./deploy
          # Copy contents from static directory to the root of deploy
          cp -r ./static/* ./deploy/
          
          # Create a .nojekyll file to disable Jekyll processing
          touch ./deploy/.nojekyll
          echo "Created .nojekyll file to disable Jekyll processing"
          
          # Copy additional files
          cp ./LICENSE ./deploy/ || echo "LICENSE file not copied"
          
          # Show contents for debugging
          echo "Contents of deploy directory:"
          ls -la ./deploy/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 