name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Debug workspace
        run: |
          echo "Current directory:"
          pwd
          echo "Files in root directory:"
          ls -la
          echo "Files in static directory:"
          ls -la ./static

      - name: Prepare deploy directory
        run: |
          mkdir -p ./deploy
          mkdir -p ./deploy/static

          # Copy static files to the static directory
          cp -r ./static/* ./deploy/static/
          
          # Copy the root index.html
          cp ./index.html ./deploy/index.html
          
          # Create a .nojekyll file to disable Jekyll processing
          touch ./deploy/.nojekyll
          echo "Created .nojekyll file to disable Jekyll processing"
          
          # Copy additional files
          cp ./LICENSE ./deploy/ || echo "LICENSE file not copied"
          
          # Remove any README.md to prevent it from being displayed
          rm -f ./deploy/README.md 2>/dev/null || true
          
          # Show contents for debugging
          echo "Contents of deploy directory:"
          ls -la ./deploy/
          echo "Contents of deploy/static directory:"
          ls -la ./deploy/static/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 